// Generates src/icons/icons.tsx from the extracted Figma "Icons v2" data files.
//
// Each file in scripts/icon-data/*.json is:
//   { "Category Name": { "Icon Label": { outlined, solid, dualtone }, ... }, ... }
// where each shape value is the *inner* SVG markup (no <svg> wrapper), already
// normalized to currentColor. Files are read in sorted filename order so the
// gallery's category order is controlled by the numeric filename prefix.
//
// Run: node scripts/gen-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = path.join(root, 'scripts', 'icon-data');
const out = path.join(root, 'src', 'icons', 'icons.tsx');

const pascal = (s) =>
  s
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');

const files = fs
  .readdirSync(dataDir)
  .filter((f) => f.endsWith('.json'))
  .sort();

const seen = new Set();
const registry = [];
let body = `// AUTO-GENERATED by scripts/gen-icons.mjs from Figma "Icons v2". Do not edit by hand.\n`;
body += `import { createIcon } from './createIcon';\n`;
body += `import type { ComponentType } from 'react';\n`;
body += `import type { IconProps, IconVariant } from './createIcon';\n\n`;

for (const file of files) {
  const categories = JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf8'));
  for (const [category, icons] of Object.entries(categories)) {
    body += `// ---- ${category} ----\n`;
    for (const [label, shapes] of Object.entries(icons)) {
      let name = pascal(label) + 'Icon';
      if (seen.has(name)) {
        let i = 2;
        while (seen.has(`${pascal(label)}${i}Icon`)) i++;
        name = `${pascal(label)}${i}Icon`;
      }
      seen.add(name);
      body += `export const ${name} = createIcon(${JSON.stringify(name)}, ${JSON.stringify(shapes)});\n`;
      registry.push({ name, category });
    }
    body += `\n`;
  }
}

body += `export interface IconMeta {\n  name: string;\n  category: string;\n  Icon: ComponentType<IconProps>;\n}\n\n`;
body += `export const iconRegistry: IconMeta[] = [\n`;
for (const r of registry) {
  body += `  { name: ${JSON.stringify(r.name)}, category: ${JSON.stringify(r.category)}, Icon: ${r.name} },\n`;
}
body += `];\n\n`;
body += `export const ICON_VARIANTS: { value: IconVariant; label: string }[] = [\n`;
body += `  { value: 'outlined', label: 'Outlined' },\n`;
body += `  { value: 'solid', label: 'Solid' },\n`;
body += `  { value: 'dualtone', label: 'Dual-tone' },\n`;
body += `  { value: 'dualtone-selected', label: 'Selected' },\n`;
body += `];\n`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`Generated ${registry.length} icons across ${files.length} data files -> ${path.relative(root, out)}`);
