// Generates src/icons/icons.tsx from the extracted Figma "Icons v2" data files.
//
// Each file in scripts/icon-data/*.json is:
//   { "Category Name": { "Icon Label": { outlined, solid, dualtone }, ... }, ... }
// where each shape value is the *inner* SVG markup (no <svg> wrapper), already
// normalized to currentColor. It is converted to JSX children here — see
// markupToJsx below for why it is not passed through as raw markup. Files are
// read in sorted filename order so the gallery's category order is controlled
// by the numeric filename prefix.
//
// Run: node scripts/gen-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = path.join(root, 'scripts', 'icon-data');
const out = path.join(root, 'src', 'icons', 'icons.tsx');

const pascal = (s) =>
  s
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');

// SVG presentation attributes can't resolve CSS var(), so theme-reactive paints
// are emitted as inline `style`. The extracted data keeps Figma's raw values
// (white knockouts, a currentColor notification dot); this maps them to tokens:
//   - A currentColor dot ringed by white (only the Notification badge matches
//     this signature) -> red dot (surface-error-primary) + surface ring.
//   - Any remaining white fill/stroke is a cut-out -> the surface the icon sits
//     on (--xui-icon-knockout, default --surface-raised), so it blends in both
//     themes instead of rendering as a white blob on dark.
const KNOCKOUT = 'var(--xui-icon-knockout, var(--surface-raised))';
const themePaints = (svg) =>
  svg
    .replaceAll(
      'fill="currentColor" stroke="white" stroke-width="1.5"',
      `style="fill:var(--surface-error-primary);stroke:${KNOCKOUT}" stroke-width="1.5"`,
    )
    .replaceAll('fill="white"', `style="fill:${KNOCKOUT}"`)
    .replaceAll('stroke="white"', `style="stroke:${KNOCKOUT}"`);

// ---- SVG markup -> JSX ------------------------------------------------------
//
// The shapes are emitted as real JSX children rather than handed to
// `dangerouslySetInnerHTML`. React compares that prop by *reference*, so a
// fresh `{ __html }` per render made every icon rewrite its own subtree —
// replacing the node under the pointer mid-click, which stopped the browser
// firing `click` at all (ADR 0011). As elements built once at module scope,
// the subtree is referentially stable and React skips it outright.
//
// The markup is machine-generated and narrow: 6 element types, ~20 attributes,
// no text nodes, no comments. A tokeniser is sufficient and keeps the
// generator dependency-free.

/** `stroke-width` -> `strokeWidth`; `data-*`/`aria-*` stay as authored. */
const camel = (n) => (/^(data|aria)-/.test(n) ? n : n.replace(/-([a-z])/g, (_, c) => c.toUpperCase()));

/** `fill:red;stroke:blue` -> `{{ fill: "red", stroke: "blue" }}` */
function styleProp(css) {
  const decls = css
    .split(';')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((decl) => {
      const i = decl.indexOf(':');
      // Values carry commas (`var(--a, var(--b))`) but never colons, so
      // splitting on the first colon is safe.
      return `${camel(decl.slice(0, i).trim())}: ${JSON.stringify(decl.slice(i + 1).trim())}`;
    });
  return `{{ ${decls.join(', ')} }}`;
}

function attrsToProps(raw) {
  let out = '';
  for (const [, name, value] of raw.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
    out += name === 'style' ? ` style=${styleProp(value)}` : ` ${camel(name)}=${JSON.stringify(value)}`;
  }
  return out;
}

const TAG = /<(\/)?([a-zA-Z][a-zA-Z0-9]*)((?:\s+[a-zA-Z-]+="[^"]*")*)\s*(\/)?>/g;

function markupToJsx(markup, pad) {
  const lines = [];
  let depth = 0;
  for (const [, closing, name, attrs, selfClose] of markup.matchAll(TAG)) {
    if (closing) {
      lines.push(pad + '  '.repeat(--depth) + `</${name}>`);
      continue;
    }
    const open = pad + '  '.repeat(depth) + `<${name}${attrsToProps(attrs)}`;
    if (selfClose) lines.push(open + ' />');
    else {
      lines.push(open + '>');
      depth++;
    }
  }
  if (depth !== 0) throw new Error(`unbalanced SVG markup: ${markup.slice(0, 80)}`);
  return lines.join('\n');
}

const SHAPES = ['outlined', 'solid', 'dualtone'];

const files = fs
  .readdirSync(dataDir)
  .filter((f) => f.endsWith('.json'))
  .sort();

const seen = new Set();
const registry = [];
let body = `// AUTO-GENERATED by scripts/gen-icons.mjs from Figma "Icons v2". Do not edit by hand.\n`;
body += `import { createIcon } from './createIcon';\n`;
body += `import type { ComponentType } from 'react';\n`;
body += `import type { IconProps, IconVariant } from './createIcon';\n\n`;

for (const file of files) {
  const categories = JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf8'));
  for (const [category, icons] of Object.entries(categories)) {
    body += `// ---- ${category} ----\n`;
    for (const [label, shapes] of Object.entries(icons)) {
      let name = pascal(label) + 'Icon';
      if (seen.has(name)) {
        let i = 2;
        while (seen.has(`${pascal(label)}${i}Icon`)) i++;
        name = `${pascal(label)}${i}Icon`;
      }
      seen.add(name);
      const missing = SHAPES.filter((s) => !shapes[s]);
      if (missing.length) throw new Error(`${label}: missing shape(s) ${missing.join(', ')}`);
      body += `export const ${name} = createIcon(${JSON.stringify(name)}, {\n`;
      for (const shape of SHAPES) {
        body += `  ${shape}: (\n    <>\n${markupToJsx(themePaints(shapes[shape]), '      ')}\n    </>\n  ),\n`;
      }
      body += `});\n`;
      registry.push({ name, category });
    }
    body += `\n`;
  }
}

body += `export interface IconMeta {\n  name: string;\n  category: string;\n  Icon: ComponentType<IconProps>;\n}\n\n`;
body += `export const iconRegistry: IconMeta[] = [\n`;
for (const r of registry) {
  body += `  { name: ${JSON.stringify(r.name)}, category: ${JSON.stringify(r.category)}, Icon: ${r.name} },\n`;
}
body += `];\n\n`;
body += `export const ICON_VARIANTS: { value: IconVariant; label: string }[] = [\n`;
body += `  { value: 'outlined', label: 'Outlined' },\n`;
body += `  { value: 'solid', label: 'Solid' },\n`;
body += `  { value: 'dualtone', label: 'Dual-tone' },\n`;
body += `  { value: 'dualtone-selected', label: 'Selected' },\n`;
body += `];\n`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`Generated ${registry.length} icons across ${files.length} data files -> ${path.relative(root, out)}`);
